
rain_id = {
200:"thunderstorm with light rain, you are strongly encouraged to bring an umbrella",
201:"thunderstorm with rain, you are strongly encouraged to bring an umbrella",
202:"thunderstorm with heavy rain, you are strongly encouraged to bring an umbrella",
210:"light thunderstorm, you are strongly encouraged to bring an umbrella",
212:"heavy thunderstorm, you are strongly encouraged to bring an umbrella",
221:"tragged thunderstorm, you are strongly encouraged to bring an umbrella",
230:"thunderstorm with light drizzle, you are strongly encouraged to bring an umbrella",
231:"thunderstorm with drizzle, you are strongly encouraged to bring an umbrella",
232:"thunderstorm with heavy drizzle, you are strongly encouraged to bring an umbrella",
300:"light intensity drizzle, you are encouraged to bring an umbrella",
301:"drizzle, you might want to bring an umbrella",
302:"heavy intensity drizzle, you are encouraged to bring an umbrella ",
310:"drizzle rain,you are encouraged to bring an umbrella",
312:"heavy intensity drizzle rain, you are strongly encouraged to bring an umbrella",
313:"shower rain and drizzle, you are strongly encouraged to bring an umbrella",
314:"heavy shower rain and drizzle, you are strongly encouraged to bring an umbrella",
321:"shower drizzle, you are strongly encouraged to bring an umbrella",
500:"light rain, you are encouraged to bring an umbrella",
501:"moderate rain, you are encouraged to bring an umbrella",
502:"heavy intensity rain, you are strongly encouraged to bring an umbrella",
503:"very heavy rain, you are strongly encouraged to bring an umbrella",
504:"extreme rain, you are strongly encouraged to bring an umbrella",
511:"freezing rain, you are strongly encouraged to bring an umbrella and bring more clothes",
520:"light intensity shower rain, you are strongly encouraged to bring an umbrella",
521:"shower rain, you are strongly encouraged to bring an umbrella",
522:"heavy intensity shower rain, you are strongly encouraged to bring an umbrella",
531:"ragged shower rain, you are strongly encouraged to bring an umbrella",
701:"haze, you are encouraged to bring a mask, do use psi command to check the psi value!",
800:"clear, do check the UVI index using uvi commands!",
801:"a few clouds, yay!",
802:"scattered clouds, yay!",
803:"broken clouds, yay!",
804:"overcast clouds, yay!",
}

uvi_index = {
    0:"low uv radiation,yay!",
    1:"low uv radiation,yay!",
    2:"low uv radiation,yay!",
    3:"moderate uv radiation, you might want to put on sunscreen!",
    4:"moderate uv radiation, you might want to put on sunscreen!",
    5:"moderate uv radiation, you might want to put on sunscreen or bring am umbrella!",
    6:"high uv radiation, you are encouraged to avoid outdoor activities if possible and put on sunscreen!",
    7:"high uv radiation, you are encouraged to avoid outdoor activities if possible and put on sunscreen!",
    8:"very high uv radiation, you are strongly encouraged to avoid outdoor activities if possible and put on sunscreen!",
    9:"very high uv radiation, you are strongly encouraged to avoid outdoor activities if possible and put on sunscreen!",
    10:"very high uv radiation, you are strongly encouraged to avoid outdoor activities if possible and put on sunscreen!",
    11:"extremely high uv radiation, you should avoid outdoor activities at all costs and put on plenty sunscreen!",
    12:"extremely high uv radiation, you should avoid outdoor activities at all costs and put on plenty sunscreen!",
    13:"extremely high uv radiation, you should avoid outdoor activities at all costs and put on plenty sunscreen!",
    14:"extremely high uv radiation, you should avoid outdoor activities at all costs and put on plenty sunscreen!",
    15:"extremely high uv radiation, you should avoid outdoor activities at all costs and put on plenty sunscreen!"

}

